name: publish

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  USERNAME: natroutter
  IMAGE: natroutter/pocketbase:latest
  VERSION: 0.29.3

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u natroutter --password-stdin
      - name: Build
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE }} \
            --build-arg PB_VERSION=${{ env.VERSION }} \
            --label "org.opencontainers.image.source=https://github.com/${{ github.repository }}" \
            --label "org.opencontainers.image.description=PocketBase Docker Image" \
            --label "org.opencontainers.image.licenses=MIT" \
            .
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}